### ISSUE TITLE
KeyError in `delete_reverse_relations_if_need`?

### ISSUE THREAD

**Issue by ckcollab** [beda-software/drf-writable-nested#52]
### Models

```python
class Competition(models.Model):
    ...

class Phase(models.Model):
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE, related_name='phases')
    ...
```

### Serializers

```
class PhaseSerializer(WritableNestedModelSerializer):
    class Meta:
        model = Phase
        fields = (
            'id',
            # Competition is no longer referenced from here, I removed it some time ago to fix something,
            # I believe?
            # 'competition',
        )


class CompetitionSerializer(WritableNestedModelSerializer):
    producer = ProducerSerializer(required=False, validators=[])
    phases = PhaseSerializer(required=False, many=True)
    
   ...

    def create(self, validated_data):
        """
        This creates *AND* updates based on the combination of (remote_id, producer)
        """
        try:
            temp_instance = Competition.objects.get(
                remote_id=validated_data.get('remote_id'),
                producer__id=self.context['producer'].id
            )
        except ObjectDoesNotExist:
            temp_instance = None
        # If we have an existing instance from this producer
        # with the same remote_id, update it instead of making a new one
        if temp_instance:
            return self.update(temp_instance, validated_data)
        else:
            new_instance = super().create(validated_data)
            new_instance.producer = self.context['producer']
            new_instance.save()
            return new_instance
```

### The problem

When creating a competition, things work fine. However, when I try to update the competition I receive this traceback:

```python
Traceback (most recent call last):
  File "/Users/eric/.virtualenvs/chahub/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/eric/.virtualenvs/chahub/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/eric/.virtualenvs/chahub/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/eric/.virtualenvs/chahub/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/eric/.virtualenvs/chahub/lib/python3.6/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/eric/.virtualenvs/chahub/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/eric/.virtualenvs/chahub/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/eric/.virtualenvs/chahub/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/eric/src/chahub/src/apps/api/views/competitions.py", line 43, in create
    self.perform_create(serializer)
  File "/Users/eric/.virtualenvs/chahub/lib/python3.6/site-packages/rest_framework/mixins.py", line 26, in perform_create
    serializer.save()
  File "/Users/eric/.virtualenvs/chahub/lib/python3.6/site-packages/rest_framework/serializers.py", line 728, in save
    self.instance = self.create(validated_data)
  File "/Users/eric/.virtualenvs/chahub/lib/python3.6/site-packages/rest_framework/serializers.py", line 700, in create
    self.child.create(attrs) for attrs in validated_data
  File "/Users/eric/.virtualenvs/chahub/lib/python3.6/site-packages/rest_framework/serializers.py", line 700, in <listcomp>
    self.child.create(attrs) for attrs in validated_data
  File "/Users/eric/src/chahub/src/apps/api/serializers/competitions.py", line 131, in create
    return self.update(temp_instance, validated_data)
  File "/Users/eric/.virtualenvs/chahub/lib/python3.6/site-packages/drf_writable_nested/mixins.py", line 272, in update
    self.delete_reverse_relations_if_need(instance, reverse_relations)
  File "/Users/eric/.virtualenvs/chahub/lib/python3.6/site-packages/drf_writable_nested/mixins.py", line 285, in delete_reverse_relations_if_need
    related_data = self.get_initial()[field_name]
KeyError: 'phases'
```

Maybe I am doing something stupid in my create method? The serializer is meant to handle creating OR updating if the model already exists.

Thanks for any help!

**Comment by ckcollab** [comment]
Ah, the problem seems to be due to using `many=True` for the main (`CompetitionSerializer`) serializer?! When using a list, it cannot get the proper instance to update?
